### ISSUE TITLE
Add more information to the README

### ISSUE THREAD

**Issue by nelsonmfinda** [RafaelGSS/node-architeture-project-design#1]
Hi, @RafaelGSS I want to contribute to this project, I noticed that the project _README_ has very little information, so we can add a _CONTRIBUTING.md_, add more sections talking about the project and so on...

**Comment by RafaelGSS** [comment]
Hello @nelsonmfinda ! Thanks for your issue.

Oh... yep. I will go create a new README with a CONTRIBUITING too. 

Obs: Today.

**Comment by nelsonmfinda** [comment]
@RafaelGSS Waiting for this man.

**Comment by RafaelGSS** [comment]
@nelsonmfinda  Updated!

Create:
-  CONTRIBUITING.md
- TODO.md

and updated README.md.

Closing this issue.
